#!/bin/sh
# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# Compiles .tex. groff (.mom, .ms), .rmd, .md.
# Opens .sent files as sent presentations.
# Runs scripts based on extention or shebang

file=$(readlink -f "$1")
dir=$(dirname "$file")
base="${file%.*}"
bases="${1%.*}"

cd "$dir" || exit

textype() { \
	command="pdflatex"
	grep -i xunicode "$file" > /dev/null && command="xelatex"
	$command --output-directory="$dir" "$base" &&
	grep -i addbibresource "$file" >/dev/null &&
	biber --input-directory "$dir" "$base" &&
	$command --output-directory="$dir" "$base" &&
	$command --output-directory="$dir" "$base"
	grep -i natbib "$file" || grep -i biblatex "$file" || grep -i apacite "$file" > /dev/null &&
	bibtex "$bases" &&
	$command --output-directory="$dir" "$base" &&
	$command --output-directory="$dir" "$base"
	}
mdown(){
        command="pandoc "$file" -o "$base".pdf -V geometry:margin=1in --pdf-engine=xelatex --filter pandoc-citeproc"
        #( sed 15q "$file" | grep -i -q 'beamer' ) && command="pandoc "$file" -o "$base".pdf --pdf-engine=xelatex -t beamer"
        grep -i beamer "$file" > /dev/null && command="pandoc "$file" -o "$base".pdf --pdf-engine=xelatex -t beamer --filter pandoc-citeproc"
	#sed 15q "$file" | grep -i -q 'beamer' ) && command="pandoc "$file" -o "$base".pdf -V geometry:margin=1in -V fontsize=12px --latex-engine=xelatex -t beamer"
        $command
}

case "$file" in
	*\.ms) refer -PS -e "$file" | groff -me -ms -kejpt -dpaper=letter -P-pletter -T pdf > "$base".pdf ;;
	*\.mom) refer -PS -e "$file" | groff -mom -kejpt -T pdf > "$base".pdf ;;
	*\.rmd) echo "require(rmarkdown); render('$file', quiet=TRUE)" | R -q --vanilla ;;
	*\.tex) textype "$file" ;;
	*\.md) mdown "$file" ;;
	*config.h) sudo make install ;;
        *\.c) cc "$file" -o "$base" && "$base" ;;
	*\.py) python "$file" ;;
	*\.go) go run "$file" ;;
	*\.sent) setsid sent "$file" 2>/dev/null & ;;
	*) sed 1q "$file" | grep "^#!/" | sed "s/^#!//" | xargs -r -I % "$file" ;;
esac
