#!/bin/sh
# Give dmenu list of all unicode characters to copy.
# Shows the selected character in dunst if running.

# Must have xclip installed to even show menu.
#xclip -h >/dev/null || exit
#
#chosen=$(grep -v "#" ~/.config/emoji | dmenu -i -l 20 -fn Monospace-15)
#
#[ "$chosen" != "" ] || exit
#
#c=$(echo "$chosen" | sed "s/ .*//")
#echo "$c" | tr -d '\n' | xclip -selection clipboard
#notify-send "'$c' copied to clipboard." &
#
#s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
#echo "$s" | tr -d '\n' | xclip
#notify-send "'$s' copied to primary." &

xclip -h 2>/dev/null || exit 1

chosen=$(cut -d ';' -f1 ~/.local/share/larbs/emoji | dmenu -i -l 20 | sed "s/ .*//")

[ "$chosen" != "" ] || exit

# If you run this command with an argument, it will automatically insert the character.
if [ -n "$1" ]; then
	xdotool key Shift+Insert
else
	echo "$chosen" | tr -d '\n' | xclip -selection clipboard
	notify-send "'$chosen' copied to clipboard." &
fi
